# Generated by Django 2.1.7 on 2019-03-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190312_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='text_align',
            field=models.CharField(default='text-right', max_length=20),
        ),
    ]
