# Generated by Django 2.1.7 on 2019-03-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_carousel_text_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='text_align',
            field=models.CharField(blank=True, default='text-right', max_length=20, null=True),
        ),
    ]
