# Generated by Django 2.1.7 on 2019-03-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190313_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='Heading',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='id',
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_num',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
