# Generated by Django 2.1.7 on 2019-03-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190313_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
