# Generated by Django 2.1.7 on 2019-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190313_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='id',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
