# Generated by Django 2.1.7 on 2019-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_carousel_carousel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_num',
            field=models.IntegerField(default=170),
        ),
    ]
